### PR TITLE
Fix edgeR_mirBase.R error

### LINKED ISSUE #187: Error in plotMDS  (edgeR_miRBase.r)
### Description of the bug

When script is checking condition to make the MDS plot, it is checking about the number of sample. 

```
 # Make MDS plot (only perform with 3 or more samples)
    if (length(filelist[[1]]) > 2){
        pdf(paste(header,"_edgeR_MDS_plot.pdf",sep=""))
        MDSdata <- plotMDS(dataNorm)
        dev.off()

```
This works in many cases but I have a situation where the length is 3 but when dataNorm is set
```
# TMM
    dataNorm <- calcNormFactors(dataDGE)
```
I get that there are only 2 columns.
I need to figure out what is wrong with the sample, but however checking should be done on the numbers of columns on **dataNorm**  and not by the filelist

### Command used and terminal output

```console
Output error


Error in plotMDS.default(y, top = top, labels = labels, pch = pch, cex = cex,  : 
  Only 2 columns of data: need at least 3
Calls: plotMDS -> plotMDS.DGEList -> plotMDS -> plotMDS.default
Execution halted
```
```


### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by atrigila**
Fixes #187 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/smrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/smrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

File: bin/edgeR_miRBase.r [hunk 1]
```diff
@@ -79,7 +79,7 @@ for (i in 1:2) {
     }
 
     # Make MDS plot (only perform with 3 or more samples)
-    if (length(filelist[[1]]) > 2){
+    if (length(ncol(dataNorm$counts)) > 2){
```
Comment (nschcolnicov) [inline bin/edgeR_miRBase.r:82]: @atrigila ncol(dataNorm$counts) returns a single integer value representing the number of columns, wouldn't wrapping it with length() always return 1? Making this condition ineffective. Shouldn't we just check ncol(dataNorm$counts) > 2 directly instead?

**Review by nschcolnicov — APPROVED** [review]
LGTM!
